default_platform(:ios)

platform :ios do
    desc "Build and upload to TestFlight"
    lane :beta do
      cocoapods(
        workspace: "BetterLyfe.xcworkspace"
      )
      build_app(
        workspace: "BetterLyfe.xcworkspace",
        scheme: "BetterLyfe"
      )
      upload_to_testflight
    end

    desc "Release to App Store"
    lane :release do
      cocoapods(
        workspace: "BetterLyfe.xcworkspace"
      )
      build_app(
        workspace: "BetterLyfe.xcworkspace",
        scheme: "BetterLyfe"
      )
      upload_to_app_store
    end
  desc "Run Jest tests"
  lane :test do
    Dir.chdir("..") do
      sh("yarn test")
    end
  end

  desc "Build the iOS app"
  lane :build do
    cocoapods(
      workspace: "BetterLyfe.xcworkspace"
    )
    gym(
      workspace: "BetterLyfe.xcworkspace",
      scheme: "BetterLyfe",
      configuration: "Release"
    )
  end
end
